int main() {
/*
what if we want somthing to run if the if does not run? That's what else is for.
you put else after the if statement
if (...) {
    ...
} else {
    ...
}
and the else block runs if the if block doesn't
*/
    int x = 42;
    // TODO: add a else block to this if statement that prints x - 2
    if (x < 42) {
        `qout("%i", x + 12);
    }
    // Don't touch below this line.
    return 0;
}

