int main() {
/*
BONUS!
If a if statement is only one line long you can omit the braces

if (i == 0) `qout("i is 0");

Quiz!
This tests: boolean logic, if/else, comparison 
You have three numbers.
TODO: Print:
"all positive" if all three numbers are greater than 0
"some positive" if at least one number is greater than 0
"none positive" if none of them are greater than 0
*/
    int x = -4;
    int y = 0;
    int z = 7;
    // TODO: write your if/else statement here
    return 0;
}
