/*
You can use different numeric types for assignments.
0b prefix = binary
int x = 0b101;
0x prefix = hex
int x = 0xDEADBEEF;
0o prefix = octal
int o = 0o767;
Bitwise logic operators directly on bits.

The bitwise logic operators are as follows:

|: Bitwise OR:
    OR's every bit
    0110 | 1000 = 1110;
&: Bitwise AND:
    AND's every bit
    0110 & 1000 = 0000;
    0101 & 1011 = 0001;
$: Bitwise XOR:
    XOR's every bit
    0110 $ 1000 = 1110;
    0101 $ 1011 = 1110;
~: Bitwise NOT:
    NOT's every bit
    ~1010 = 0101
*/
int main() {
    `qout("No challenge, just read the lesson text");
    return 0;
}
