int main() {
/*
the float type stores a 7 digit floating point number.
Floating point means the decimal position can change, eg

```
123.0
12.032
```
Fixed point means the decimal is stationary

```
123.000
002.320
```

Float _literals_ (values) end in f.
the double type is like the float type, except it doesn't have a `f` and is 15ish digits.
*/
    // TODO: Create a float, f, storing the first 4 digits of pi (3.141)
    
    // TODO: Create a double, d, storing the first 6 digits of pi (3.14159)
    
    // Don't touch below this line
    `qout("%f, %d", f, d);
    return 0;
}
