/*
Tuples can be _destructured_, which puts their values into a series of lvalues.

(int, int){ x, y } = mytuple;

If x and y are undeclared, it declares them, and if they are, then it assigns the variables the values.

You can also use this to declare multiple variables at once.

(int, string){ x, y } = (0, "");

*/
int main() {
    `qout("No challenge, just read lesson text\n");
    return 0;
}
